spring:
  datasource:
    url: jdbc:postgresql://172.18.15.30:5432/restful?searchpath=restful&charset=utf8
    username: restful
    password: restfuldbuserlogin
    driver-class-name: org.postgresql.Driver

mybatis:
  typeAliasesPackage: springboot.domain
  mapperLocations: classpath:mapper/*.xml